version: "3.8"

services:
  tester:
    image: cimg/python:3.9.9
    # stdin_open: true
    # tty: true
    depends_on:
      # https://stackoverflow.com/a/55835081
      postgres:
        condition: service_healthy

  postgres:
    image: cimg/postgres:12.9    
    ports:
      - "5534:5534"
    environment:
      POSTGRES_DB: sl_pg
      POSTGRES_HOST: localhost
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGPORT: 5534
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 15
    depends_on:
      - rethinkdb-backend
      - rethinkdb-frontend
      - influxdb
      - elasticsearch

  rethinkdb-backend:
    image: rethinkdb:2.4.0
    ports:
      - "5555:28015"

  rethinkdb-frontend:
    image: rethinkdb:2.4.0
    ports:
      - "5550:28015"

  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - "8086:8086"

  elasticsearch:
    image: elasticsearch:7.17.0
    ports:
      - "9222:9200"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms256m -Xmx256m
