version: 2.1
  
workflows:
  version: 2
  run-tests:
    jobs:
      - test
      
jobs:
  test:
    docker:
      - image: cimg/python:3.9.9
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
      - image: cimg/postgres:12.9
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_DB: test_db
          POSTGRES_USER: db_user
          POSTGRES_PASSWORD: db_password
          PGPORT: 5534
      - image: rethinkdb:2.4.0
        name: rethinkdb-backend
        command: ["rethinkdb", "--bind", "all", "--driver-port", "5555"]
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
      - image: rethinkdb:2.4.0
        name: rethinkdb-frontend
        command: ["rethinkdb", "--bind", "all", "--driver-port", "5550"]
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
      - image: influxdb:1.8-alpine
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          INFLUXDB_HTTP_BIND_ADDRESS: 0.0.0.0:8086
      - image: elasticsearch:7.17.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          discovery.type: single-node
          ES_JAVA_OPTS: "-Xms256m -Xmx256m"
          http.port: 9222
    steps:
      - checkout
      - run:
          name: Check Postgres connection
          environment:
            DISABLE_PSQL_SSL: true
          command: |
            sudo apt-get update
            sudo apt-get install -y postgresql-client
            psql postgresql://db_user:db_password@0.0.0.0:5534/test_db < .circleci/test-db/schema.sql
      - restore_cache:
          key: deps-python-${{ .Branch }}-${{ checksum "setup.py" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            python -m pip install --upgrade pip
            python -m pip install "setuptools==57.4.0"
            python -m pip install --upgrade wheel
            python -m pip install spacy
            # python -m spacy download en_core_web_sm
      - save_cache:
          key: deps-python-${{ .Branch }}-${{ checksum "setup.py" }}
          paths:
            - venv
