version: 2.1
  
workflows:
  version: 2
  run-tests:
    jobs:
      - test
      
jobs:
  test:
    docker:
      - image: python:3.9.10
      - image: cimg/postgres:12.9
        environment:
          POSTGRES_DB: test_db
          POSTGRES_USER: db_user
          POSTGRES_PASSWORD: db_password
          PGPORT: 5534
      - image: rethinkdb:2.4.0
        name: rethinkdb-backend
        # command: ["rethinkdb", "--bind", "all", "--driver-port", "5555"]
        command:
          - rethinkdb
          - --bind
          - all
          - --driver-port
          - 15555
      - image: rethinkdb:2.4.0
        name: rethinkdb-frontend
        # command: ["rethinkdb", "--bind", "all", "--driver-port", "5550"]
        command: rethinkdb --bind all --driver-port 15550"
      - image: influxdb:1.8-alpine
        environment:
          INFLUXDB_HTTP_BIND_ADDRESS: 0.0.0.0:8086
      - image: elasticsearch:7.17.0
        environment:
          discovery.type: single-node
          ES_JAVA_OPTS: "-Xms256m -Xmx256m"
          http.port: 9222
    steps:
      - checkout
      - restore_cache:
          key: deps-dockerhub-${{ .Branch }}-${{ checksum "setup.py" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            python -m pip install --upgrade pip
            python -m pip install "setuptools==57.4.0"
            python -m pip install --upgrade wheel
            python -m pip install spacy
      - save_cache:
          key: deps-dockerhub-${{ .Branch }}-${{ checksum "setup.py" }}
          paths:
            - venv
      - run:
          name: Check Postgres connection
          environment:
            DISABLE_PSQL_SSL: true
          command: |
            apt-get update
            apt-get install -y postgresql-client
            psql postgresql://db_user:db_password@0.0.0.0:5534/test_db < .circleci/test-db/schema.sql
