version: 2.1

orbs:
  python: circleci/python@2.0.1

jobs:
  test:
    docker:
      - image: cimg/python:3.8.12-browsers
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD 
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Set alias
          command: |
            which python
            alias python=$(which python3)
            which python
      - run: which python
      - run: 
          name: Persist alias
          command: echo "alias python=$(which python3)" >> $BASH_ENV
      - run: which python
      # - restore_cache:
      #     key: venv-${{ arch }}-${{ .Branch }}-${{ checksum "setup.py" }}
      # - run:
      #     name: Install dependencies
      #     command: |
      #       python -m venv venv
      #       source venv/bin/activate
      #       python -m pip install --upgrade pip
      #       python -m pip install "setuptools==57.4.0"
      #       python -m pip install --upgrade wheel
      #       pip install --use-feature=2020-resolver -e ".[dev]"
      #       python -m spacy download en_core_web_sm
      # - save_cache:
      #     key: venv-${{ arch }}-${{ checksum "setup.py" }}
      #     paths:
      #       - venv
      # - run:
      #     name: Run tests
      #     environment:
      #       DISABLE_PSQL_SSL: true
      #       SL_BASE: ..
      #     command: |
      #       # source venv/bin/activate
      #       docker-compose -f .circleci/docker-compose.yml up -d
      #       sudo apt-get update
      #       sudo apt-get install -y postgresql-client
      #       psql postgresql://test:test@localhost:5534/sl_pg < .circleci/test-db/schema.sql
      #       # pytest --skip-slow
  machine-test:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run: 
          name: Set alias
          command: |
            which python
            alias python=$(which python3)
            which python
      - run: which python
      - run: 
          name: Persist alias
          command: echo "alias python=$(which python3)" >> $BASH_ENV
      - run: which python
      # - run:
      #     name: Run tests
      #     environment:
      #       DISABLE_PSQL_SSL: true
      #       SL_BASE: ..
      #     command: |
      #       docker-compose -f .circleci/docker-compose.yml up -d
      #       sudo apt-get update
      #       sudo apt-get install -y postgresql-client
      #       psql postgresql://test:test@localhost:5534/sl_pg < .circleci/test-db/schema.sql

workflows:
  version: 2
  run-tests:
    jobs:
      # - test
      - machine-test
      