name: pre-commit hooks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: checkout sl
      uses: actions/checkout@v2
      with:
        lfs: false

    - name: set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: run static analysis
      run: |
        pre-commit run --all-files
