name: Sync Develop
on:
  push:
    branches:
      - staging

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing develop branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.2.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "staging"
          TO_BRANCH: "develop"
